enum ResponseCode {
  SUCCESS = "SU",
  VALIDATION_FAILED = "VF",
  DUPLICATION_EMAIL = "DE",
  DUPLICATION_TEL_NUMBER = "DT",
  DUPLICATION_NICKNAME = "DN",
  NOT_EXISTED_USER = "NU",
  NOT_EXISTED_BOARD = "NB",
  LOGIN_FAILED = "LF",
  AUTHORIZATION_FAILED = "AF",
  NO_PERMISION = "NP",
  DATABASE_ERROR = "DBE",
}

export default ResponseCode;
